# Generated by Django 3.1.7 on 2021-04-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECAD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('image', 'IMAGE'), ('stl', 'STL'), ('N/A', 'n/a')], default='n/a', max_length=6),
        ),
    ]
