# Generated by Django 3.1.7 on 2021-04-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECAD', '0002_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('stl', 'STL'), ('image', 'IMAGE'), ('n/a', 'N/A')], default='N/A', max_length=6),
        ),
    ]
